require 'controllers/base-controller.rb'
require 'controllers/country-controller.rb'
require 'controllers/state-controller.rb'
require 'controllers/city-controller.rb'
require 'controllers/center-controller.rb'
require 'controllers/table-controller.rb'
